name: chesscom_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none
repository: https://github.com/V3ntus/chesscom_dart

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http:
  logging:
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
